_wandb:
    value:
        cli_version: 0.22.2
        e:
            75hu67lcjlk5oclt808nql3gs37n4sog:
                codePath: src/mlops_p1/train.py
                codePathLocal: src/mlops_p1/train.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "250685575168"
                        used: "211028160512"
                email: francesco100mo@gmail.com
                executable: /Users/francescocentomo/anaconda3/envs/MLOPS_p1/bin/python
                git:
                    commit: 450dc3b85b5e351776ff4f47c22f5a1976f4a156
                    remote: https://github.com/fracent/MLOPS_p1.git
                host: MacBookPro.home
                memory:
                    total: "8589934592"
                os: macOS-10.16-x86_64-i386-64bit
                program: /Users/francescocentomo/Desktop/MLOPS/MLOPS_p1/src/mlops_p1/train.py
                python: CPython 3.12.11
                root: /Users/francescocentomo/Desktop/MLOPS/MLOPS_p1
                startedAt: "2025-10-22T15:17:28.238941Z"
                writerId: 75hu67lcjlk5oclt808nql3gs37n4sog
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 1
                - 5
                - 53
                - 105
            "2":
                - 1
                - 5
                - 53
                - 105
            "3":
                - 16
            "4": 3.12.11
            "5": 0.22.2
            "12": 0.22.2
            "13": darwin-x86_64
batch_size:
    value: 32
epochs:
    value: 5
lr:
    value: 0.001
